//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeatBeatSchedule
    {
        public System.Guid BeatBeatScheduleID { get; set; }
        public System.Guid BeatID { get; set; }
        public System.Guid BeatScheduleID { get; set; }
    
        public virtual Beat Beat { get; set; }
        public virtual BeatSchedule BeatSchedule { get; set; }
    }
}
