//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beat()
        {
            this.BeatBeatSchedules = new HashSet<BeatBeatSchedule>();
            this.Contracts = new HashSet<Contract>();
        }
    
        public System.Guid BeatID { get; set; }
        public bool Active { get; set; }
        public System.Data.Entity.Spatial.DbGeography BeatExtent { get; set; }
        public int FreewayID { get; set; }
        public string BeatDescription { get; set; }
        public string BeatNumber { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<bool> IsTemporary { get; set; }
        public string BeatColor { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeatBeatSchedule> BeatBeatSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
