//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public System.Guid ContractID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal MaxObligation { get; set; }
        public string AgreementNumber { get; set; }
        public System.Guid BeatID { get; set; }
        public System.Guid ContractorID { get; set; }
    
        public virtual Beat Beat { get; set; }
        public virtual Contractor Contractor { get; set; }
    }
}
