//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverStatu
    {
        public System.Guid DriverStatusID { get; set; }
        public string DriverName { get; set; }
        public string VehicleID { get; set; }
        public string Status { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string BeatNumber { get; set; }
        public string ScheduleName { get; set; }
    }
}
