//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarlyRollIn
    {
        public System.Guid RollInID { get; set; }
        public System.Guid DriverID { get; set; }
        public System.DateTime DateStamp { get; set; }
        public string Explanation { get; set; }
        public string CHPLogNumber { get; set; }
        public System.Guid BeatID { get; set; }
        public string VehicleID { get; set; }
        public string ExceptionType { get; set; }
    }
}
