//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportServer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public System.Guid IncidentID { get; set; }
        public string ApproximateLocation { get; set; }
        public int FreewayID { get; set; }
        public Nullable<System.Guid> LocationID { get; set; }
        public System.Guid BeatSegmentID { get; set; }
        public Nullable<System.TimeSpan> TimeStamp { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public System.Guid CreatedBy { get; set; }
        public string Description { get; set; }
        public string IncidentNumber { get; set; }
        public System.DateTime LastModified { get; set; }
        public string Location { get; set; }
        public string CrossStreet1 { get; set; }
        public string CrossStreet2 { get; set; }
        public string Direction { get; set; }
        public string BeatNumber { get; set; }
        public string DispatchNumber { get; set; }
    }
}
