//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportServer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fspEntities : DbContext
    {
        public fspEntities()
            : base("name=fspEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeatBeatSchedule> BeatBeatSchedules { get; set; }
        public virtual DbSet<Beat> Beats { get; set; }
        public virtual DbSet<BeatSchedule> BeatSchedules { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Incident> Incidents { get; set; }
        public virtual DbSet<Contractor> Contractors { get; set; }
    }
}
