<?xml version="1.0" encoding="utf-8"?><Database Name="fsp" Class="FSPDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=38.124.164.211,5815;Initial Catalog=fsp;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="fspConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.IncidentTypes" Member="IncidentTypes">
    <Type Name="IncidentType">
      <Column Name="IncidentTypeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IncidentTypeCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="IncidentType" Member="IncidentType1" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>